### ISSUE TITLE
在部分情况下会出现错误

### ISSUE THREAD

**Issue by mq00fc** [EasilyNET/Hoyo.Ocr#13]
在部分情况下会出现如下错误
{
    "statusCode": "InternalServerError",
    "msg": "startIndex cannot be larger than length of string. (Parameter 'startIndex')",
    "data": null
}

另：如果身份证的角度旋转了90°则也会出现如上问题，请问可以解决吗？谢谢！

**Comment by joesdu** [comment]
这个只是个实验性的项目🥲,并没有研究过到底要如何才能正确识别.我知道一个[专业做OCR的项目](https://github.com/sdcb/PaddleSharp).对于身份证的识别我也没有深入研究.

**Comment by joesdu** [comment]
> 在部分情况下会出现如下错误 { "statusCode": "InternalServerError", "msg": "startIndex cannot be larger than length of string. (Parameter 'startIndex')", "data": null }
> 
> 另：如果身份证的角度旋转了90°则也会出现如上问题，请问可以解决吗？谢谢！

身份证旋转的问题,可以尝试客户端限制他拍照的方式.

**Comment by mq00fc** [comment]
> 这个只是个实验性的项目🥲,并没有研究过到底要如何才能正确识别.我知道一个[专业做OCR的项目](https://github.com/sdcb/PaddleSharp).对于身份证的识别我也没有深入研究.

非常感谢您的开源，我自己研究一下
